baseURL = "/"
title   = "Raphaël Stevens"
languageCode = "fr-fr"
theme = "hello-friend-ng"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# disqusShortname = ""
# cloudflareWebAnalytics = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params.author]
  name = "Raphaël Stevens"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[[imports]]
path = ""

[params]
  firstname = "Raphaël"
  lastname = "Stevens"
  EnableLanguageToggle = true
  counterdev = "da44b53c-3920-4a97-bf68-2c45cfa2defb"
  ogimage = "/img/background-rs.jpg"
  sitename = "Raphaël Stevens"
  twitter = "@collapsology"
  description = "Essayiste // Prospectiviste. Bio | Recherche | Artivisme | Publications | Contact"
  images = [""]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
 
  # backgroundImage = ""

  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  enableThemeToggle = true
  # defaultTheme = "dark"
  enableSharingButtons = true
  enableGlobalLanguageMenu = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  [params.footer]
    trademark = "2024"
    rss = false
    copyright = false
    author = true

   topText = ['''Made <a href="https://github.com/raphaelstevens/raphaelstevens">with</a>&nbsp; <svg class="heart-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" style="fill: red; vertical-align: middle; position: relative; top: -0.1em;"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>''']
    bottomText = []

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark        = " "
    logoText        = "Home"
    logoHomeLink    = "/"
    logoCursorColor = "#86C885"

  # [params.commento]
  #   url = ""

  #[params.portrait]
  #  path     = "img/raphael-stevens.jpg"
  #  alt      = "© Jérôme Panconi"
  #  maxWidth = "130px"


[languages]
  [languages.fr]
    disabled = false
    languageCode = "fr-FR"
    languageDirection = "ltr"
    languageName = "fr"
    title = "Raphaël Stevens"
    weight = 1
  [languages.fr.params]
    homeSubtitle  = "Essayiste // Prospectiviste"
 [[languages.fr.menu.main]]
    identifier = "about"
    name       = "Bio"
    url        = "about/"
	weight    = 1
[[languages.fr.menu.main]]
    identifier = "recherche"
    name       = "Recherche"
    url        = "recherche/"
	weight    = 2
[[languages.fr.menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "publications/"
	weight    = 4
[[languages.fr.menu.main]]
    identifier = "artivisme"
    name       = "Artivisme"
    url        = "artivisme/"
	weight    = 3
[[languages.fr.menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "contact/"
	weight    = 5

[[languages.fr.params.social]]
  name = "twitter"
  url = "https://twitter.com/collapsology"  

[[languages.fr.params.social]]
      name = "email"
      url = "contact/"  

  [languages.en]
    disabled = false
    languageCode = "en-us"
    languageDirection = "ltr"
    languageName = "en"
    title = "Raphaël Stevens"
    weight = 2
  [languages.en.params]
    homeSubtitle  = "Essayist // Prospectivist"
   [[languages.en.menu.main]]
	 identifier = "about"
     name       = "About"
     url        = "about/"
	 weight    = 1
   [[languages.en.menu.main]]
	 identifier = "recherche"
     name       = "Research"
     url        = "recherche/"
	 weight    = 2
   [[languages.en.menu.main]]
	 identifier = "artivisme"
     name       = "Artivism"
     url        = "artivisme/"
	 weight    = 3
	 [[languages.en.menu.main]]
	 identifier = "publications"
     name       = "Publications"
     url        = "publications/"
	 weight    = 4
   [[languages.en.menu.main]]
	 identifier = "contact"
     name       = "Contact"
     url        = "contact/"
	 weight    = 5

[[languages.en.params.social]]
  name = "twitter"
  url = "https://twitter.com/collapsology"  

[[languages.en.params.social]]
      name = "email"
      url = "contact"  


